FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv && apt-get clean
WORKDIR /app
COPY . /app
RUN python3 -m venv /app/venv && /app/venv/bin/pip install --no-cache-dir -r requirements.txt
ENV PATH="/app/venv/bin:$PATH"
EXPOSE 8000
CMD ["python3", "app.py"]